name: Release

on:
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  build-deploy:
    uses: ./.github/workflows/tests.yml
    secrets: inherit