name: Test-Build-Publish

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Install dependencies
      run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
    - name: Run tests
      run: bundle exec rake
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results

  build:
    name: "Build and Publish Gem"
    needs: test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'no-publish')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Publish to RubyGems
      run: |
        mkdir -p ~/.gem
        touch ~/.gem/credentials
        chmod 0600 ~/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > ~/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        RUBYGEMS_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"