name: Test-Build-Publish

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    environment: RUBY DEPLOY
    steps:
    - uses: actions/checkout@v3
      with:
          persist-credentials: false
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gem-
          
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Install dependencies
      run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
    - name: Run tests
      run: bundle exec rake
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results

    - uses: actions/setup-node@v2
      with:
        node-version: "20.x"
    - name: Semantic Release      
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
      run: |
        npm install -g semantic-release@23.0.8
        npm install -g @semantic-release/changelog@6.0.3
        npm install -g @semantic-release/git@10.0.1
        npm install -g @semantic-release/error@4.0.0
        npm install -g @semantic-release/exec@6.0.3
        npm install -g @semantic-release/github@10.0.3
        npm install -g @semantic-release/release-notes-generator@13.0.0
        npm install -g semantic-release-rubygem@1.2.0
        npm install -g @droidsolutions-oss/semantic-release-update-file@1.4.0
        semantic-release

  # build:
  #   name: "Build and Publish Gem"
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: "!contains(github.event.head_commit.message, 'no-publish')"
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Ruby
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: 3.0.0
  #   - name: Publish to RubyGems
  #     run: |
  #       mkdir -p ~/.gem
  #       touch ~/.gem/credentials
  #       chmod 0600 ~/.gem/credentials
  #       printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > ~/.gem/credentials
  #       gem build *.gemspec
  #     env:
  #       RUBYGEMS_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"