name: "PR Validations"

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚨 Invalid Pull Request Title!\n\nBut don't worry, you need to follow semantic release PR title.\n\nIf you are fixing something use \`fix: here your message\`\nIf you are adding new behaviour use \`feat: here your message\`.`
            })