name: PR Validations

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - master
      - develop

permissions:
  pull-requests: read
  
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  build:
    name: "Build"
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Build Gem
      run: |
        gem build *.gemspec