name: Release

on:
  push:
    branches:
      - master
      - release

jobs:
  test:
    name: "Tests"
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  build-deploy:
    name: "Build & Deploy"
    needs: test
    uses: ./.github/workflows/build-deploy.yml
    secrets: inherit
