name: Release

on:
  push:
    branches:
      - develop

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  build-deploy:    
    needs: test
    uses: ./.github/workflows/build-deploy.yml
    secrets: inherit
