name: Tests

on:
  workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    environment: RUBY DEPLOY
    steps:
      - uses: ./.github/actions/setup-ruby
      
      - name: Run tests
        run: bundle exec rake

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results