name: Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: RUBY DEPLOY
    steps:
      - uses: actions/checkout@v3
      - uses: ./github/actions/setup-ruby/action.yml
      
      - name: Run tests
        run: bundle exec rake

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results